version: "3.3"

services:
  keycloak-vue3:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DOCKER_ENV: dev
    image:
      keycloak-vue3
    ports:
      - "8081:8081"
    volumes:
      - ./app:/app
    command: >
      sh -c "npm run serve"
    mem_limit: 4g
